### PR TITLE
load environment variables - fix #14

### LINKED ISSUE #14: Cannot build on Fedora Silverblue 30
I am unable to build the wireguard kernel module on Fedora Silverblue 30.

It appears to be an issue with the checksum after it downloads the wireguard package:

`sha256sum: 'standard input': no properly formatted SHA256 checksum lines found
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now`

Interesting, the build will complete successfully when I download the Dockerfile to my system, then run the `podman build` command from the `atomic-wireguard-module` script.

Here is a [link](https://1drv.ms/t/s!AilSk027aY9KjpQ1O_u1TKac5r2xtw) to the output of `atomic-wireguard-module build`
Thank you!

### PR DESCRIPTION
**Pull request by shadowofsilicon**
This should fix the issue #14

### CODE REVIEW

**Comment by jdoss** [comment]
Thanks for opening this PR @shadowofsilicon. I appreciate it a lot. I wonder if something changed in systemd on Silverblue. The systemd unit for `atomic-wireguard.service` https://github.com/jdoss/atomic-wireguard/blob/master/atomic-wireguard.service#L9 should load the envvars when the unit is called.

**Comment by jdoss** [comment]
@shadowofsilicon can you let me know what version of systemd is running on Silverblue right now?

**Comment by shadowofsilicon** [comment]
I’m not at my machine right now, but it should match the current package for regular FC30, which according to apps.fedoraproject.org/packages is systemd-241-8.git9ef65cb.fc30

**Comment by jdoss** [comment]
I merged the other PR. Let's close this one for now as I fixes the two things that are preventing people from using the project.

**Pull request closed without merging**
